production:
  host: localhost
  adapter: postgresql
  database: cloudalarm
  username: alarmuser
  password: alarmpassword

development:
  host: localhost
  adapter: postgresql
  database: cloudalarm
  username: alarmuser
  password: alarmpassword

test:
  host: localhost
  adapter: postgresql
  database: cloudalarm
  username: alarmuser
  password: alarmpassword
